# 5 — Exercices autonomes : choisir une option

Ce notebook accompagne le deck **Atelier individuel — après-midi**. Les
quatre options sont indépendantes : choisissez-en une, ouvrez ses slides,
puis produisez seulement la preuve demandée.

| Option | Travail | Preuve finale |
|---|---|---|
| A | deux fonctions pandas | trois assertions |
| B | une classe dans `temperature_tools.py` | import neuf et résultat |
| C | une fonction et trois tests `unittest` | commande terminée par `OK` |
| D | boucle Python et NumPy | résultats égaux et deux médianes |

Les cellules de contrôle restent exécutables avant que les TODO soient
terminés. Un message « à compléter » signifie que l'option n'est pas encore
validée. N'utilisez **Exécuter tout** qu'après avoir terminé l'option choisie.

In [2]:
from pathlib import Path
import importlib
import subprocess
import sys
import timeit

import numpy as np
import pandas as pd

print("Python:", sys.version.split()[0])
print("Working directory:", Path.cwd())
print("NumPy:", np.__version__, "pandas:", pd.__version__)

Python: 3.12.6
Working directory: j:\DEV\G404-Data_TD_manips-diverses-comprehension\Manips_exos_python
NumPy: 2.5.3 pandas: 3.0.5


## Option A — Deux fonctions et des valeurs manquantes

Lire les slides 5–8 du deck de l'après-midi. Compléter les deux fonctions.
`known_minutes` retire seulement les valeurs manquantes.
`fraction_at_or_above` réutilise la première fonction et inclut le seuil.
Zéro est une valeur connue.

In [2]:
values = pd.Series(
    [0, 120, pd.NA, 180],
    dtype="Float64"
)

print(values)
# values.describe()

0      0.0
1    120.0
2     <NA>
3    180.0
dtype: Float64


In [3]:
def known_minutes(values: pd.Series) -> pd.Series:
    """Return the observed minute values."""
    return values.dropna()

print(known_minutes(values))

def fraction_at_or_above(values: pd.Series, threshold: float) -> float:
    """Return the fraction of observed values at or above threshold."""
    known = known_minutes(values)

    if known.empty:
        return 0.0

    return float((known >= threshold).sum()) / len(known)

print(fraction_at_or_above(values, 120))

0      0.0
1    120.0
3    180.0
dtype: Float64
0.6666666666666666


In [4]:
option_a_ready = False
try:
    clean = known_minutes(values)
    fraction = fraction_at_or_above(values, 180)
    assert isinstance(clean, pd.Series)
    assert clean.tolist() == [0, 120, 180]
    assert clean.mean() == 100
    assert np.isclose(fraction, 1 / 3)
    option_a_ready = True
    print("Option A validée.")
except Exception as error:
    print(f"Option A à compléter: {type(error).__name__}: {error}")

Option A validée.


## Option B — Une classe dans un module

Lire les slides 9–12. Construire d'abord la classe dans la cellule suivante.
Elle conserve une **copie float** des températures Fahrenheit et renvoie un
tableau NumPy en degrés Celsius. Après validation, créer manuellement
`temperature_tools.py` dans le même dossier et y déplacer la classe avec
son import NumPy. La définition finale ne doit rester que dans le module.

In [5]:
class TemperatureSeries:
    """Store Fahrenheit values and convert them to Celsius."""

    def __init__(self, fahrenheit: np.ndarray):
        self.fahrenheit = np.asarray(fahrenheit, dtype=float)

    def celsius(self) -> np.ndarray:
        return(self.fahrenheit - 32) * 5 / 9

test = TemperatureSeries(np.array([32, 68, 86]))
print(test.fahrenheit)
print(test.celsius())

[32. 68. 86.]
[ 0. 20. 30.]


In [6]:
option_b_class_ready = False
try:
    source = np.array([32, 68, 86])
    series = TemperatureSeries(source)
    source[0] = 999
    assert series.fahrenheit.dtype.kind == "f"
    assert series.fahrenheit.tolist() == [32.0, 68.0, 86.0]
    assert np.allclose(series.celsius(), [0, 20, 30])
    option_b_class_ready = True
    print("Classe validée dans le notebook. Déplacez-la maintenant dans temperature_tools.py.")
except Exception as error:
    print(f"Classe à compléter: {type(error).__name__}: {error}")

Classe validée dans le notebook. Déplacez-la maintenant dans temperature_tools.py.


Dans `temperature_tools.py`, conserver seulement l'import et la classe :

```python
import numpy as np

class TemperatureSeries:
    # Move your completed class here.
    ...
```

Enregistrer le fichier, **redémarrer le noyau**, puis exécuter la cellule
d'import ci-dessous sans exécuter auparavant la définition de classe du
notebook. Le chemin affiché doit désigner votre fichier.

In [3]:
import scripts_py.temperature_tools as tt

series = tt.TemperatureSeries(
    np.array([32, 68, 86])
    )

print(series.celsius())
print(tt.__file__)

[ 0. 20. 30.]
j:\DEV\G404-Data_TD_manips-diverses-comprehension\Manips_exos_python\scripts_py\temperature_tools.py


In [4]:
option_b_import_ready = False
try:
    importlib.invalidate_caches()
    import scripts_py.temperature_tools as tt

    imported_series = tt.TemperatureSeries(np.array([32, 68, 86]))
    assert np.allclose(imported_series.celsius(), [0, 20, 30])
    print("Imported from:", tt.__file__)
    option_b_import_ready = True
    print("Option B validée.")
except Exception as error:
    print(f"Import à compléter: {type(error).__name__}: {error}")

Imported from: j:\DEV\G404-Data_TD_manips-diverses-comprehension\Manips_exos_python\scripts_py\temperature_tools.py
Option B validée.


## Option C — Une fonction et trois tests `unittest`

Lire les slides 13–16. Créer deux fichiers dans le même dossier :

```text
delay_tools.py
test_delay_tools.py
```

Dans `delay_tools.py`, écrire `delay_minutes(actual, promised)`. La fonction
ne renvoie jamais de délai négatif. Dans `test_delay_tools.py`, importer la
fonction réelle et écrire trois méthodes commençant par `test_` pour les cas
`25, 30`, `45, 45` et `42, 30`. Ne recopiez pas la fonction dans le test.

In [5]:
option_c_ready = False
expected_files = [Path("delay_tools.py"), Path("test_delay_tools.py")]
if not all(path.is_file() for path in expected_files):
    print("Option C à compléter: créer delay_tools.py et test_delay_tools.py.")
else:
    completed = subprocess.run(
        [sys.executable, "-m", "unittest", "-v", "test_delay_tools.py"],
        text=True,
        capture_output=True,
    )
    print(completed.stdout)
    print(completed.stderr)
    option_c_ready = completed.returncode == 0 and "Ran 3 tests" in completed.stderr
    print("Option C validée." if option_c_ready else "Corriger le premier test en échec.")

Option C à compléter: créer delay_tools.py et test_delay_tools.py.


## Option D — Boucle Python ou NumPy

Lire les slides 17–19. Compléter deux fonctions qui divisent les mêmes
valeurs par 60. Vérifier leur égalité **avant** la mesure. Les données sont
créées hors du chronomètre ; chaque mesure inclut le calcul et la création
du résultat.

In [6]:
values = np.arange(300_000, dtype=float)

def loop_hours(values: list[float]) -> list[float]:
    """Convert minute values with an explicit Python loop."""
    result = []
    for value in values:
        result.append(value/60)
    return result

display(loop_hours(values.tolist()[:7]))

def numpy_hours(values: np.ndarray) -> np.ndarray:
    """Convert all values with one NumPy expression."""
    return  values / 60.0

display(numpy_hours(values[:7]).tolist())

[0.0,
 0.016666666666666666,
 0.03333333333333333,
 0.05,
 0.06666666666666667,
 0.08333333333333333,
 0.1]

[0.0,
 0.016666666666666666,
 0.03333333333333333,
 0.05,
 0.06666666666666667,
 0.08333333333333333,
 0.1]

In [18]:
option_d_ready = False
values_array = np.arange(300_000, dtype=float)
values_list = values_array.tolist()

try:
    loop_result = loop_hours(values_list)
    numpy_result = numpy_hours(values_array)
    assert len(loop_result) == len(values_array)
    assert np.asarray(numpy_result).shape == values_array.shape
    assert np.allclose(loop_result, numpy_result)

    loop_times = timeit.repeat(
        lambda: loop_hours(values_list), repeat=5, number=1
    )
    numpy_times = timeit.repeat(
        lambda: numpy_hours(values_array), repeat=5, number=1
    )
    loop_median = float(np.median(loop_times))
    numpy_median = float(np.median(numpy_times))
    option_d_ready = True
    print(f"Boucle Python — médiane: {loop_median * 1000:.3f} ms")
    print(f"NumPy — médiane: {numpy_median * 1000:.3f} ms")
    print("Option D validée. Limitez votre conclusion à cette machine, cette taille et ce calcul.")
except Exception as error:
    print(f"Option D à compléter: {type(error).__name__}: {error}")

Boucle Python — médiane: 40.913 ms
NumPy — médiane: 1.343 ms
Option D validée. Limitez votre conclusion à cette machine, cette taille et ce calcul.


## Preuve finale

Conserver uniquement la preuve correspondant à l'option choisie :

- **A :** les trois assertions passent et vous expliquez le rôle de zéro et de `pd.NA` ;
- **B :** l'import part de `temperature_tools.py` après redémarrage et renvoie `[0, 20, 30]` ;
- **C :** `python -m unittest -v` exécute trois tests et termine par `OK` ;
- **D :** les résultats sont égaux, les deux médianes sont affichées et la conclusion décrit le protocole.

Notez en quelques phrases ce que vous avez construit, la preuve obtenue et,
si nécessaire, le dernier blocage exact.

## DIVERS tests

In [7]:
def test_conversion (w:float, h:float) -> float:
    return h + w

result = float(test_conversion(1,5))

print(result)
print(type(result))
print(type(result).__name__)

assert type(result).__name__ == 'float'

6.0
<class 'float'>
float
